const fs = require('fs');
const path = require('path');

class CodeReview {
  constructor() {
    this.guidelines = this.loadGuidelines();
  }

  loadGuidelines() {
    try {
      const claudePath = path.join(process.cwd(), 'CLAUDE.md');
      if (fs.existsSync(claudePath)) {
        const content = fs.readFileSync(claudePath, 'utf8');
        return this.parseGuidelines(content);
      }
      console.warn('CLAUDE.md not found, using default guidelines');
      return this.getDefaultGuidelines();
    } catch (error) {
      console.error('Error loading guidelines:', error);
      return this.getDefaultGuidelines();
    }
  }

  parseGuidelines(content) {
    // 简单解析CLAUDE.md内容，提取核心原则
    const guidelines = {
      thinkBeforeCoding: [],
      simplicityFirst: [],
      surgicalChanges: [],
      goalDrivenExecution: []
    };

    const sections = content.split('## ');
    sections.forEach(section => {
      if (section.includes('1. Think Before Coding') || section.includes('思考后编码')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.thinkBeforeCoding = lines;
      } else if (section.includes('2. Simplicity First') || section.includes('简单优先')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.simplicityFirst = lines;
      } else if (section.includes('3. Surgical Changes') || section.includes('外科手术式修改')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.surgicalChanges = lines;
      } else if (section.includes('4. Goal-Driven Execution') || section.includes('目标驱动执行')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.goalDrivenExecution = lines;
      }
    });

    return guidelines;
  }

  getDefaultGuidelines() {
    return {
      thinkBeforeCoding: [
        '明确陈述假设，不确定时提问而不是猜测',
        '呈现多种解释，避免在存在歧义时默默选择',
        '在有必要时提出反对意见，如果有更简单的方法',
        '当困惑时停止，明确指出不清楚的地方并请求澄清'
      ],
      simplicityFirst: [
        '只实现被要求的功能，不添加额外特性',
        '不为一次性代码创建抽象',
        '不添加未被请求的"灵活性"或"可配置性"',
        '不为不可能的场景添加错误处理',
        '如果200行代码可以精简为50行，就重写它'
      ],
      surgicalChanges: [
        '不"改进"相邻代码、注释或格式',
        '不重构未损坏的代码',
        '匹配现有风格，即使你会以不同方式做',
        '如果你注意到无关的死代码，提及它但不要删除它',
        '只删除你的更改导致未使用的导入/变量/函数'
      ],
      goalDrivenExecution: [
        '定义成功标准，循环直到验证',
        '将命令式任务转换为可验证的目标',
        '对于多步骤任务，陈述简短计划',
        '强大的成功标准让LLM独立循环，而弱标准（如"让它工作"）需要不断澄清'
      ]
    };
  }

  reviewCode(filePath, content) {
    const issues = [];

    // 检查思考后编码原则
    issues.push(...this.checkThinkBeforeCoding(content));

    // 检查简单优先原则
    issues.push(...this.checkSimplicityFirst(content));

    // 检查外科手术式修改原则
    issues.push(...this.checkSurgicalChanges(content));

    // 检查目标驱动执行原则
    issues.push(...this.checkGoalDrivenExecution(content));

    // 检查自动生成代码的质量
    issues.push(...this.checkAutoGeneratedCode(content));

    // 检查系统复杂性
    issues.push(...this.checkSystemComplexity(content));

    return {
      filePath,
      issues,
      totalIssues: issues.length,
      timestamp: new Date().toISOString()
    };
  }

  checkThinkBeforeCoding(content) {
    const issues = [];

    // 检查是否有明确的假设陈述
    if (!content.includes('// 假设') && !content.includes('/* 假设') && !content.includes('假设:')) {
      issues.push({
        severity: 'info',
        category: 'thinkBeforeCoding',
        message: '建议添加明确的假设陈述，说明代码的前提条件和约束'
      });
    }

    // 检查是否有多种解决方案的比较
    if (!content.includes('// 方案') && !content.includes('/* 方案') && !content.includes('方案:')) {
      issues.push({
        severity: 'info',
        category: 'thinkBeforeCoding',
        message: '建议添加多种解决方案的比较，说明选择当前方案的理由'
      });
    }

    return issues;
  }

  checkSimplicityFirst(content) {
    const issues = [];

    // 检查代码长度
    const lines = content.split('\n').length;
    if (lines > 500) {
      issues.push({
        severity: 'warning',
        category: 'simplicityFirst',
        message: `代码长度较长（${lines}行），建议拆分为更小的函数或模块`
      });
    }

    // 检查不必要的抽象
    if (content.includes('class') && content.includes('abstract') && lines < 100) {
      issues.push({
        severity: 'info',
        category: 'simplicityFirst',
        message: '对于简短的代码，考虑是否真的需要抽象类'
      });
    }

    // 检查未使用的导入
    const importLines = content.match(/import\s+.*?;/g) || [];
    const usedImports = new Set();
    
    // 简单检查导入是否被使用
    importLines.forEach(importLine => {
      const importName = importLine.match(/import\s+(.*?)\s+from/) || importLine.match(/import\s+.*?{\s*(.*?)\s*}/);
      if (importName) {
        const name = importName[1].trim();
        if (!content.includes(name) && !content.includes(name.split(',')[0].trim())) {
          issues.push({
            severity: 'warning',
            category: 'simplicityFirst',
            message: `未使用的导入: ${name}`
          });
        }
      }
    });

    return issues;
  }

  checkSurgicalChanges(content) {
    const issues = [];

    // 检查代码风格一致性
    const indentation = content.match(/^\s+/m);
    if (indentation) {
      const indent = indentation[0];
      const lines = content.split('\n');
      let inconsistentIndent = false;
      
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.trim() && line.startsWith(' ')) {
          const lineIndent = line.match(/^\s+/)[0];
          if (lineIndent !== indent) {
            inconsistentIndent = true;
            break;
          }
        }
      }
      
      if (inconsistentIndent) {
        issues.push({
          severity: 'warning',
          category: 'surgicalChanges',
          message: '代码缩进不一致，建议保持统一的缩进风格'
        });
      }
    }

    // 检查是否修改了无关代码
    const commentChanges = content.match(/\/\*[\s\S]*?\*\//g) || [];
    if (commentChanges.length > 5) {
      issues.push({
        severity: 'info',
        category: 'surgicalChanges',
        message: '修改了较多注释，确保只修改与功能相关的注释'
      });
    }

    return issues;
  }

  checkGoalDrivenExecution(content) {
    const issues = [];

    // 检查是否有明确的成功标准
    if (!content.includes('// 成功标准') && !content.includes('/* 成功标准') && !content.includes('成功标准:')) {
      issues.push({
        severity: 'info',
        category: 'goalDrivenExecution',
        message: '建议添加明确的成功标准，说明代码的预期行为'
      });
    }

    // 检查是否有测试代码
    if (!content.includes('test') && !content.includes('Test') && !content.includes('describe')) {
      issues.push({
        severity: 'info',
        category: 'goalDrivenExecution',
        message: '建议添加测试代码，验证代码是否符合预期'
      });
    }

    return issues;
  }

  checkAutoGeneratedCode(content) {
    const issues = [];

    // 检查是否为自动生成的代码
    if (content.includes('// 自动生成') || content.includes('/* 自动生成') || content.includes('generated by')) {
      // 检查是否有设计说明
      if (!content.includes('// 设计说明') && !content.includes('/* 设计说明') && !content.includes('设计说明:')) {
        issues.push({
          severity: 'warning',
          category: 'autoGenerated',
          message: '自动生成的代码缺少设计说明，建议添加详细的设计文档'
        });
      }

      // 检查是否有多方案比较
      if (!content.includes('// 方案比较') && !content.includes('/* 方案比较') && !content.includes('方案比较:')) {
        issues.push({
          severity: 'info',
          category: 'autoGenerated',
          message: '自动生成的代码缺少方案比较，建议添加多种解决方案的分析'
        });
      }
    }

    return issues;
  }

  checkSystemComplexity(content) {
    const issues = [];

    // 检查函数复杂度
    const functions = content.match(/function\s+\w+\s*\([^)]*\)|const\s+\w+\s*=\s*\([^)]*\)\s*=>|class\s+\w+/g) || [];
    if (functions.length > 20) {
      issues.push({
        severity: 'warning',
        category: 'systemComplexity',
        message: `文件中函数/类数量较多（${functions.length}个），建议拆分到多个文件`
      });
    }

    // 检查嵌套深度
    const lines = content.split('\n');
    let maxDepth = 0;
    let currentDepth = 0;
    
    for (const line of lines) {
      const openBraces = (line.match(/{/g) || []).length;
      const closeBraces = (line.match(/}/g) || []).length;
      currentDepth += openBraces - closeBraces;
      maxDepth = Math.max(maxDepth, currentDepth);
    }
    
    if (maxDepth > 5) {
      issues.push({
        severity: 'warning',
        category: 'systemComplexity',
        message: `代码嵌套深度较深（${maxDepth}层），建议减少嵌套，提高可读性`
      });
    }

    // 检查循环复杂度
    const loops = (content.match(/for\s*\(|while\s*\(|do\s*{/g) || []).length;
    const conditionals = (content.match(/if\s*\(|else if\s*\(|switch\s*\(/g) || []).length;
    const totalComplexity = loops + conditionals;
    
    if (totalComplexity > 30) {
      issues.push({
        severity: 'warning',
        category: 'systemComplexity',
        message: `代码循环复杂度较高（${totalComplexity}），建议简化逻辑`
      });
    }

    return issues;
  }

  reviewDirectory(directoryPath) {
    const results = [];
    
    function processFile(filePath) {
      try {
        const content = fs.readFileSync(filePath, 'utf8');
        const result = this.reviewCode(filePath, content);
        results.push(result);
      } catch (error) {
        console.error(`Error reviewing file ${filePath}:`, error);
      }
    }

    function processDirectory(dirPath) {
      const files = fs.readdirSync(dirPath);
      
      for (const file of files) {
        const fullPath = path.join(dirPath, file);
        const stats = fs.statSync(fullPath);
        
        if (stats.isDirectory() && file !== 'node_modules' && file !== '.git') {
          processDirectory(fullPath);
        } else if (stats.isFile() && (file.endsWith('.js') || file.endsWith('.ts') || file.endsWith('.jsx') || file.endsWith('.tsx'))) {
          processFile.call(this, fullPath);
        }
      }
    }

    processDirectory.call(this, directoryPath);
    
    return {
      results,
      totalFiles: results.length,
      totalIssues: results.reduce((sum, result) => sum + result.totalIssues, 0),
      timestamp: new Date().toISOString()
    };
  }

  generateReport(reviewResults) {
    let report = `# 代码审查报告\n\n`;
    report += `生成时间: ${new Date().toISOString()}\n`;
    report += `审查文件数: ${reviewResults.totalFiles}\n`;
    report += `发现问题数: ${reviewResults.totalIssues}\n\n`;

    reviewResults.results.forEach(result => {
      if (result.issues.length > 0) {
        report += `## ${result.filePath}\n`;
        report += `问题数: ${result.issues.length}\n\n`;
        
        result.issues.forEach((issue, index) => {
          report += `${index + 1}. [${issue.severity.toUpperCase()}] ${issue.category}: ${issue.message}\n`;
        });
        
        report += `\n`;
      }
    });

    return report;
  }
}

module.exports = CodeReview;