const fs = require('fs');
const path = require('path');

class CodingAssistant {
  constructor() {
    this.guidelines = this.loadGuidelines();
  }

  loadGuidelines() {
    try {
      const claudePath = path.join(process.cwd(), 'CLAUDE.md');
      if (fs.existsSync(claudePath)) {
        const content = fs.readFileSync(claudePath, 'utf8');
        return this.parseGuidelines(content);
      }
      console.warn('CLAUDE.md not found, using default guidelines');
      return this.getDefaultGuidelines();
    } catch (error) {
      console.error('Error loading guidelines:', error);
      return this.getDefaultGuidelines();
    }
  }

  parseGuidelines(content) {
    const guidelines = {
      thinkBeforeCoding: [],
      simplicityFirst: [],
      surgicalChanges: [],
      goalDrivenExecution: []
    };

    const sections = content.split('## ');
    sections.forEach(section => {
      if (section.includes('1. Think Before Coding') || section.includes('思考后编码')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.thinkBeforeCoding = lines;
      } else if (section.includes('2. Simplicity First') || section.includes('简单优先')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.simplicityFirst = lines;
      } else if (section.includes('3. Surgical Changes') || section.includes('外科手术式修改')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.surgicalChanges = lines;
      } else if (section.includes('4. Goal-Driven Execution') || section.includes('目标驱动执行')) {
        const lines = section.split('\n').filter(line => line.trim() && !line.startsWith('#'));
        guidelines.goalDrivenExecution = lines;
      }
    });

    return guidelines;
  }

  getDefaultGuidelines() {
    return {
      thinkBeforeCoding: [
        '明确陈述假设，不确定时提问而不是猜测',
        '呈现多种解释，避免在存在歧义时默默选择',
        '在有必要时提出反对意见，如果有更简单的方法',
        '当困惑时停止，明确指出不清楚的地方并请求澄清'
      ],
      simplicityFirst: [
        '只实现被要求的功能，不添加额外特性',
        '不为一次性代码创建抽象',
        '不添加未被请求的"灵活性"或"可配置性"',
        '不为不可能的场景添加错误处理',
        '如果200行代码可以精简为50行，就重写它'
      ],
      surgicalChanges: [
        '不"改进"相邻代码、注释或格式',
        '不重构未损坏的代码',
        '匹配现有风格，即使你会以不同方式做',
        '如果你注意到无关的死代码，提及它但不要删除它',
        '只删除你的更改导致未使用的导入/变量/函数'
      ],
      goalDrivenExecution: [
        '定义成功标准，循环直到验证',
        '将命令式任务转换为可验证的目标',
        '对于多步骤任务，陈述简短计划',
        '强大的成功标准让LLM独立循环，而弱标准（如"让它工作"）需要不断澄清'
      ]
    };
  }

  getCodingSuggestions(content, filePath) {
    const suggestions = [];

    // 思考后编码建议
    suggestions.push(...this.getThinkBeforeCodingSuggestions(content));

    // 简单优先建议
    suggestions.push(...this.getSimplicityFirstSuggestions(content));

    // 外科手术式修改建议
    suggestions.push(...this.getSurgicalChangesSuggestions(content));

    // 目标驱动执行建议
    suggestions.push(...this.getGoalDrivenExecutionSuggestions(content));

    // 自动生成代码建议
    suggestions.push(...this.getAutoGeneratedCodeSuggestions(content));

    // 系统复杂性建议
    suggestions.push(...this.getSystemComplexitySuggestions(content));

    return {
      filePath,
      suggestions,
      totalSuggestions: suggestions.length,
      timestamp: new Date().toISOString()
    };
  }

  getThinkBeforeCodingSuggestions(content) {
    const suggestions = [];

    // 建议添加假设陈述
    if (!content.includes('// 假设') && !content.includes('/* 假设') && !content.includes('假设:')) {
      suggestions.push({
        type: 'thinkBeforeCoding',
        message: '建议添加明确的假设陈述，说明代码的前提条件和约束',
        example: '// 假设: 输入参数为有效的JSON对象，且包含必要的字段'
      });
    }

    // 建议添加方案比较
    if (!content.includes('// 方案') && !content.includes('/* 方案') && !content.includes('方案:')) {
      suggestions.push({
        type: 'thinkBeforeCoding',
        message: '建议添加多种解决方案的比较，说明选择当前方案的理由',
        example: '// 方案比较: 选择方案A因为它更简单且性能更好，虽然方案B更灵活'
      });
    }

    return suggestions;
  }

  getSimplicityFirstSuggestions(content) {
    const suggestions = [];

    // 检查代码长度
    const lines = content.split('\n').length;
    if (lines > 500) {
      suggestions.push({
        type: 'simplicityFirst',
        message: `代码长度较长（${lines}行），建议拆分为更小的函数或模块`,
        example: '// 建议: 将此文件拆分为多个功能模块，每个模块负责一个具体功能'
      });
    }

    // 检查未使用的导入
    const importLines = content.match(/import\s+.*?;/g) || [];
    importLines.forEach(importLine => {
      const importName = importLine.match(/import\s+(.*?)\s+from/) || importLine.match(/import\s+.*?{\s*(.*?)\s*}/);
      if (importName) {
        const name = importName[1].trim();
        if (!content.includes(name) && !content.includes(name.split(',')[0].trim())) {
          suggestions.push({
            type: 'simplicityFirst',
            message: `未使用的导入: ${name}，建议删除`,
            example: '// 移除未使用的导入: import ${name} from \'some-module\''
          });
        }
      }
    });

    // 检查不必要的变量
    const variableDeclarations = content.match(/(const|let|var)\s+([a-zA-Z_$][a-zA-Z0-9_$]*)\s*=/g) || [];
    variableDeclarations.forEach(declaration => {
      const variableName = declaration.match(/(const|let|var)\s+([a-zA-Z_$][a-zA-Z0-9_$]*)\s*=/)[2];
      // 简单检查变量是否被使用（排除声明行）
      const declarationLine = content.indexOf(declaration);
      const contentAfterDeclaration = content.substring(declarationLine + declaration.length);
      if (!contentAfterDeclaration.includes(variableName)) {
        suggestions.push({
          type: 'simplicityFirst',
          message: `未使用的变量: ${variableName}，建议删除`,
          example: '// 移除未使用的变量: const ${variableName} = value;'
        });
      }
    });

    return suggestions;
  }

  getSurgicalChangesSuggestions(content) {
    const suggestions = [];

    // 检查代码风格一致性
    const indentation = content.match(/^\s+/m);
    if (indentation) {
      const indent = indentation[0];
      const lines = content.split('\n');
      let inconsistentLines = [];
      
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.trim() && line.startsWith(' ')) {
          const lineIndent = line.match(/^\s+/)[0];
          if (lineIndent !== indent) {
            inconsistentLines.push(i + 1);
          }
        }
      }
      
      if (inconsistentLines.length > 0) {
        suggestions.push({
          type: 'surgicalChanges',
          message: `代码缩进不一致，建议保持统一的缩进风格（第${inconsistentLines.join(', ')}行）`,
          example: '// 建议: 使用一致的缩进风格，与文件其他部分保持一致'
        });
      }
    }

    return suggestions;
  }

  getGoalDrivenExecutionSuggestions(content) {
    const suggestions = [];

    // 建议添加成功标准
    if (!content.includes('// 成功标准') && !content.includes('/* 成功标准') && !content.includes('成功标准:')) {
      suggestions.push({
        type: 'goalDrivenExecution',
        message: '建议添加明确的成功标准，说明代码的预期行为',
        example: '// 成功标准: 函数应返回有效的JSON对象，包含所有必要的字段'
      });
    }

    // 建议添加测试代码
    if (!content.includes('test') && !content.includes('Test') && !content.includes('describe')) {
      suggestions.push({
        type: 'goalDrivenExecution',
        message: '建议添加测试代码，验证代码是否符合预期',
        example: '// 测试: 编写单元测试验证函数的各种输入情况'
      });
    }

    return suggestions;
  }

  getAutoGeneratedCodeSuggestions(content) {
    const suggestions = [];

    // 检查自动生成的代码
    if (content.includes('// 自动生成') || content.includes('/* 自动生成') || content.includes('generated by')) {
      // 建议添加设计说明
      if (!content.includes('// 设计说明') && !content.includes('/* 设计说明') && !content.includes('设计说明:')) {
        suggestions.push({
          type: 'autoGenerated',
          message: '自动生成的代码缺少设计说明，建议添加详细的设计文档',
          example: '// 设计说明: 此代码自动生成，用于处理X功能，采用Y算法'
        });
      }

      // 建议添加方案比较
      if (!content.includes('// 方案比较') && !content.includes('/* 方案比较') && !content.includes('方案比较:')) {
        suggestions.push({
          type: 'autoGenerated',
          message: '自动生成的代码缺少方案比较，建议添加多种解决方案的分析',
          example: '// 方案比较: 生成此代码时考虑了A和B两种方案，选择A因为它更适合当前场景'
        });
      }
    }

    return suggestions;
  }

  getSystemComplexitySuggestions(content) {
    const suggestions = [];

    // 检查函数复杂度
    const functions = content.match(/function\s+\w+\s*\([^)]*\)|const\s+\w+\s*=\s*\([^)]*\)\s*=>|class\s+\w+/g) || [];
    if (functions.length > 20) {
      suggestions.push({
        type: 'systemComplexity',
        message: `文件中函数/类数量较多（${functions.length}个），建议拆分到多个文件`,
        example: '// 建议: 将相关函数分组，拆分为多个模块文件'
      });
    }

    // 检查嵌套深度
    const lines = content.split('\n');
    let maxDepth = 0;
    let currentDepth = 0;
    
    for (const line of lines) {
      const openBraces = (line.match(/{/g) || []).length;
      const closeBraces = (line.match(/}/g) || []).length;
      currentDepth += openBraces - closeBraces;
      maxDepth = Math.max(maxDepth, currentDepth);
    }
    
    if (maxDepth > 5) {
      suggestions.push({
        type: 'systemComplexity',
        message: `代码嵌套深度较深（${maxDepth}层），建议减少嵌套，提高可读性`,
        example: '// 建议: 使用提前返回、提取函数等方式减少嵌套深度'
      });
    }

    // 检查循环复杂度
    const loops = (content.match(/for\s*\(|while\s*\(|do\s*{/g) || []).length;
    const conditionals = (content.match(/if\s*\(|else if\s*\(|switch\s*\(/g) || []).length;
    const totalComplexity = loops + conditionals;
    
    if (totalComplexity > 30) {
      suggestions.push({
        type: 'systemComplexity',
        message: `代码循环复杂度较高（${totalComplexity}），建议简化逻辑`,
        example: '// 建议: 将复杂逻辑拆分为多个函数，使用更简洁的条件表达式'
      });
    }

    return suggestions;
  }

  generateCodeTemplate(taskDescription) {
    // 基于任务描述生成代码模板
    const template = {
      header: `// 自动生成的代码模板
// 任务: ${taskDescription}
// 生成时间: ${new Date().toISOString()}

`,
      assumptions: `// 假设:
// 1. 输入参数的格式和类型
// 2. 预期的输出格式
// 3. 可能的边界情况

`,
      solutionComparison: `// 方案比较:
// 方案A: 简单直接的实现
// 方案B: 更灵活但复杂的实现
// 选择方案: A (理由: 简单直接，满足需求)

`,
      code: `// 实现代码
function solution() {
  // TODO: 实现具体逻辑
}

`,
      successCriteria: `// 成功标准:
// 1. 功能正确实现
// 2. 代码风格符合规范
// 3. 性能满足要求
// 4. 测试通过

`,
      tests: `// 测试代码
function testSolution() {
  // TODO: 编写测试用例
}
`
    };

    return Object.values(template).join('');
  }

  getRefactoringSuggestions(content) {
    const suggestions = [];

    // 检查重复代码
    const lines = content.split('\n');
    const lineGroups = [];
    const minGroupSize = 3;

    for (let i = 0; i < lines.length - minGroupSize; i++) {
      const group = lines.slice(i, i + minGroupSize).join('\n');
      let count = 1;
      
      for (let j = i + minGroupSize; j < lines.length - minGroupSize; j++) {
        const compareGroup = lines.slice(j, j + minGroupSize).join('\n');
        if (group === compareGroup) {
          count++;
        }
      }
      
      if (count > 1 && !lineGroups.includes(group)) {
        lineGroups.push(group);
        suggestions.push({
          type: 'refactoring',
          message: '发现重复代码，建议提取为函数',
          example: `// 建议: 将重复代码提取为函数\nfunction commonFunction() {\n${group}\n}`
        });
      }
    }

    // 检查过长的函数
    const functions = content.match(/function\s+\w+\s*\([^)]*\)\s*{[\s\S]*?}|const\s+\w+\s*=\s*\([^)]*\)\s*=>\s*{[\s\S]*?}|class\s+\w+\s*{[\s\S]*?}/g) || [];
    functions.forEach(func => {
      const funcLines = func.split('\n').length;
      if (funcLines > 50) {
        suggestions.push({
          type: 'refactoring',
          message: `函数过长（${funcLines}行），建议拆分为多个小函数`,
          example: '// 建议: 将函数拆分为多个职责单一的小函数'
        });
      }
    });

    return suggestions;
  }

  analyzeCodeQuality(content) {
    const qualityMetrics = {
      complexity: this.calculateComplexity(content),
      readability: this.calculateReadability(content),
      maintainability: this.calculateMaintainability(content),
      bestPractices: this.checkBestPractices(content)
    };

    return {
      qualityMetrics,
      overallScore: this.calculateOverallScore(qualityMetrics),
      timestamp: new Date().toISOString()
    };
  }

  calculateComplexity(content) {
    const lines = content.split('\n').length;
    const functions = content.match(/function\s+\w+\s*\([^)]*\)|const\s+\w+\s*=\s*\([^)]*\)\s*=>|class\s+\w+/g) || [];
    const loops = (content.match(/for\s*\(|while\s*\(|do\s*{/g) || []).length;
    const conditionals = (content.match(/if\s*\(|else if\s*\(|switch\s*\(/g) || []).length;
    
    const complexity = (functions.length * 2) + (loops * 1.5) + (conditionals * 1) + (lines * 0.1);
    return Math.min(10, Math.max(0, 10 - complexity / 10));
  }

  calculateReadability(content) {
    const lines = content.split('\n');
    const commentLines = lines.filter(line => line.trim().startsWith('//') || line.trim().startsWith('/*') || line.trim().endsWith('*/')).length;
    const commentRatio = commentLines / lines.length;
    
    // 检查缩进一致性
    const indentation = content.match(/^\s+/m);
    let consistentIndent = 1;
    if (indentation) {
      const indent = indentation[0];
      let inconsistentLines = 0;
      
      for (const line of lines) {
        if (line.trim() && line.startsWith(' ')) {
          const lineIndent = line.match(/^\s+/)[0];
          if (lineIndent !== indent) {
            inconsistentLines++;
          }
        }
      }
      
      consistentIndent = Math.max(0, 1 - (inconsistentLines / lines.length));
    }
    
    const readability = (commentRatio * 3) + (consistentIndent * 7);
    return Math.min(10, Math.max(0, readability));
  }

  calculateMaintainability(content) {
    const functions = content.match(/function\s+\w+\s*\([^)]*\)|const\s+\w+\s*=\s*\([^)]*\)\s*=>|class\s+\w+/g) || [];
    const functionAverageLength = functions.length > 0 ? content.split('\n').length / functions.length : 0;
    
    // 检查命名规范
    const camelCaseVariables = (content.match(/(const|let|var)\s+[a-z][a-zA-Z0-9]*\s*=/g) || []).length;
    const totalVariables = (content.match(/(const|let|var)\s+\w+\s*=/g) || []).length;
    const namingConvention = totalVariables > 0 ? camelCaseVariables / totalVariables : 1;
    
    const maintainability = (namingConvention * 5) + (Math.max(0, 1 - functionAverageLength / 50) * 5);
    return Math.min(10, Math.max(0, maintainability));
  }

  checkBestPractices(content) {
    let score = 10;
    
    // 检查是否使用严格模式
    if (!content.includes('use strict')) {
      score -= 1;
    }
    
    // 检查是否有未捕获的异常
    if (content.includes('throw') && !content.includes('try') && !content.includes('catch')) {
      score -= 1;
    }
    
    // 检查是否使用const和let而不是var
    if (content.includes('var ')) {
      score -= 1;
    }
    
    // 检查是否有console.log（生产代码中应避免）
    if (content.includes('console.log')) {
      score -= 1;
    }
    
    return Math.max(0, score);
  }

  calculateOverallScore(metrics) {
    const weights = {
      complexity: 0.3,
      readability: 0.3,
      maintainability: 0.25,
      bestPractices: 0.15
    };
    
    let totalScore = 0;
    for (const [metric, score] of Object.entries(metrics)) {
      totalScore += score * weights[metric];
    }
    
    return Math.round(totalScore * 10) / 10;
  }
}

module.exports = CodingAssistant;